# example config passed into eagle console from landing zone creator
# following variables available to terraform creation
# see ec-configuration-file-tf in tb-gcp repo for how this is populated
activator_folder_id: ${module.folder_structure.activators_id}
billing_account: ${var.billing_account_id}
region: ${var.region}
terraform_state_bucket: ${var.terraform_state_bucket_name}
env_data: input.tfvars
ec_project_name: ${module.shared_projects.shared_ec_name}
activator_terraform_code_store: ${google_sourcerepo_repository.activator-terraform-code-store.name}
shared_vpc_host_project: ${module.shared_projects.shared_networking_id}
shared_network_name: ${var.shared_vpc_name}
shared_networking_id: ${module.shared_projects.shared_networking_id}