# example config passed into eagle console from landing zone creator
# following variables available to terraform creation
# see ec-configuration-file-tf in tb-gcp repo for how this is populated
activator_folder_id: ${module.folder_structure.activators_id}
billing_account:
region: europe-west-2
terraform_state_bucket: tbase-terraform
env_data: input.tfvars
ec_project_name: tbase_ci
activator_terraform_code_store: ${google_sourcerepo_repository.activator-terraform-code-store.name}
shared_vpc_host_project: ${module.shared_projects.shared_networking_id}
shared_network_name: ${var.shared_vpc_name}
shared_networking_id: ${module.shared_projects.shared_networking_id}