openapi: 3.0.0
info:
  description: TranquilityBase GCP DAC REST API Service
  version: "1.2"
  title: TB GCP DAC

paths:
  /health:
    get:
      operationId: gcpdac.health.check
      tags:
        - health
      summary: health check
      description: health check
      responses:
        '200':
          description: Successful

  /metadata:
    get:
      operationId: gcpdac.metadata.read_all
      tags:
        - metadata
      summary: read all metadata
      description: read all metadata
      responses:
        '200':
          description: Successful

  /solution_async/:
    post:
      operationId: gcpdac.solution.create_async
      tags:
        - solution
      summary: Create a solution
      description: Create solution in more detail - TODO
      responses:
        '201':
          description: Successfully started a solution creation task
      requestBody:
        $ref: "#/components/requestBodies/solution.solutionDetails"

  "/solution_async/{oid}":
    delete:
      operationId: gcpdac.solution.delete_async
      tags:
        - solution
      summary: delete a solution
      description: delete a solution and its resources
      parameters:
        - name: oid
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successfully started a solution deletion task

  "/solution_async/result/create/{taskid}":
    get:
      operationId: gcpdac.solution.create_solution_result
      tags:
        - solution
      summary: get create solution result
      description:  get create solution result
      parameters:
        - name: taskid
          in: path
          required: true
          schema:
            type: string
      responses:
        "201":
          description: Successfully created a solution

  "/solution_async/result/delete/{taskid}":
    get:
      operationId: gcpdac.solution.delete_solution_result
      tags:
        - solution
      summary: get delete solution result
      description:  get delete solution result
      parameters:
        - name: taskid
          in: path
          required: true
          schema:
            type: string
      responses:
        "201":
          description: Successfully deleted a solution

  /folder_async/:
    post:
      operationId: gcpdac.folder.create_async
      tags:
        - folder
      summary: Create a folder
      description: Create a folder
      responses:
        '201':
          description: Successfully started a folder creation task
      requestBody:
        $ref: "#/components/requestBodies/folder.folderDetails"

  "/folder_async/{oid}":
    delete:
      operationId: gcpdac.folder.delete_async
      tags:
        - folder
      summary: delete a folder
      description: delete a folder and its resources
      parameters:
        - name: oid
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully started a folder deletion task

  "/folder_async/result/create/{taskid}":
    get:
      operationId: gcpdac.folder.create_folder_result
      tags:
        - folder
      summary: get create folder result
      description:  get create folder result
      parameters:
        - name: taskid
          in: path
          required: true
          schema:
            type: string
      responses:
        "201":
          description: Successfully created a folder

  "/folder_async/result/delete/{taskid}":
    get:
      operationId: gcpdac.folder.delete_folder_result
      tags:
        - folder
      summary: get delete folder result
      description:  get delete folder result
      parameters:
        - name: taskid
          in: path
          required: true
          schema:
            type: string
      responses:
        "201":
          description: Successfully deleted a folder


  /vpn_async/aws/:
    post:
      operationId: gcpdac.vpn.create_async_aws
      tags:
        - vpn
      summary: Create a VPN - remote aws
      description: Create VPN
      responses:
        '201':
          description: Successfully started a VPN creation task
      requestBody:
        $ref: "#/components/requestBodies/vpnAws.vpnDetails"

  /vpn_async/onprem/:
    post:
      operationId: gcpdac.vpn.create_async_onprem
      tags:
        - vpn
      summary: Create a VPN - remote on prem
      description: Create VPN
      responses:
        '201':
          description: Successfully started a VPN creation task
      requestBody:
        $ref: "#/components/requestBodies/vpnOnPrem.vpnDetails"

  "/vpn_async/{oid}":
    delete:
      operationId: gcpdac.vpn.delete_async
      tags:
        - vpn
      summary: delete a vpn
      description: delete a vpn and its resources
      parameters:
        - name: oid
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successfully started a vpn deletion task

  "/vpn_async/result/create/{taskid}":
    get:
      operationId: gcpdac.vpn.create_vpn_result
      tags:
        - vpn
      summary: get create vpn result
      description:  get create vpn result
      parameters:
        - name: taskid
          in: path
          required: true
          schema:
            type: string
      responses:
        "201":
          description: Successfully created a vpn

  "/vpn_async/result/delete/{taskid}":
    get:
      operationId: gcpdac.vpn.delete_vpn_result
      tags:
        - vpn
      summary: get delete vpn result
      description:  get delete vpn result
      parameters:
        - name: taskid
          in: path
          required: true
          schema:
            type: string
      responses:
        "201":
          description: Successfully deleted a vpn


servers:
  - url: /api
components:
  requestBodies:
    solution.solutionDetails:
      content:
        application/json:
          schema:
            x-body-name: solutionDetails
            $ref: "#/components/schemas/Solution"
    folder.folderDetails:
      content:
        application/json:
          schema:
            x-body-name: folderDetails
            $ref: "#/components/schemas/Folder"
    vpnAws.vpnDetails:
      content:
        application/json:
          schema:
            x-body-name: vpnDetails
            $ref: "#/components/schemas/VpnAws"
    vpnOnPrem.vpnDetails:
      content:
        application/json:
          schema:
            x-body-name: vpnDetails
            $ref: "#/components/schemas/VpnOnPrem"
  schemas:
    Solution:
      type: object
      properties:
        id:
          type: integer
          description: the solution id
        name:
          type: string
          description: name
        description:
          type: string
          description: description
        businessUnit:
          type: string
          description: businessUnit
        costCentre:
          type: string
          description: costCentre
        ci:
          type: string
          description: ci
        cd:
          type: string
          description: cd
        deploymentFolderId:
          type: string
          description: deployment folder id
        sourceControl:
          type: string
          description: sourceControl
        environments:
          type: array
          description: environments
          items:
            properties:
              environment:
                type: string
                description: environment
        active:
          type: boolean
          description: active
        favourite:
          type: boolean
          description: favourite
        teams:
          type: integer
          description: teams
        lastUpdated:
          type: string
          description: "UTC/CUT last updated datetime stamp see: https://github.com/tranquilitybase-io/tb-houston-service/wiki/UTC-Timestamp"
    Folder:
      type: object
      properties:
        folder:
          type: object
          properties:
            folderName:
              type: string
              description: folder name
            parentFolderId:
              type: string
              description: parent folder id
      example:
        {
          folder: {
            folderName: 'ABC',
            parentFolderId: '236823'
          }
        }
    VpnAws:
      type: object
      properties:
        id:
          type: string
          description: VPN id
        vpnCore:
          description: VPN settings
          $ref: "#/components/schemas/VpnCore"
        googleEndpoint:
          description: Google Endpoint
          $ref: "#/components/schemas/VpnGoogleEndpoint"
        amazonEndpoint:
          description: Amazon Endpoint
          $ref: "#/components/schemas/VpnAmazonEndpoint"
    VpnOnPrem:
      type: object
      properties:
        id:
          type: string
          description: VPN id
        vpnCore:
          description: VPN settings
          $ref: "#/components/schemas/VpnCore"
        googleEndpoint:
          description: Google Endpoint
          $ref: "#/components/schemas/VpnGoogleEndpoint"
        onPremEndpoint:
          description: On Premise Endpoint
          $ref: "#/components/schemas/VpnOnPremiseEndpoint"
    VpnCore:
      type: object
      properties:
        bgpInterfaceNetLength:
          type: string
          description: BGP Interface Net Length
        bgpRoutingMode:
          type: string
          description: BGP Routing Mode
        cloudRouterName:
          type: string
          description: Cloud Router Name
        description:
          type: string
          description: Description
        externalVpnGateway:
          type: string
          description: External VPN Gateway
        googleASN:
          type: integer
          description: Google ASN
        haVpnGateway:
          type: string
          description: HA VPN Gateway
        peerASN:
          type: integer
          description: Peer ASN
        projectName:
          type: string
          description: Project Name
        subnetMode:
          type: string
          description: Subnet Mode
        vpcName:
          type: string
          description: VPC Name
    VpnGoogleEndpoint:
      type: object
      properties:
        primaryGcpVpcSubnet:
          type: string
          description: Primary GCP VPC Subnet
        primaryRegion:
          type: string
          description: Primary Region
        primarySubnetName:
          type: string
          description: Primary Subnet Name
        secondaryGcpVpcSubnet:
          type: string
          description: Secondary GCP VPC Subnet
        secondaryRegion:
          type: string
          description: Secondary Region
        secondarySubnetName:
          type: string
          description: Secondary Subnet Name
    VpnAmazonEndpoint:
      # TODO check fields below
      properties:
        primaryBgpPeer:
          type: string
          description: Primary BGP Peer
        primaryPeerIp:
          type: string
          description: Primary Peer IP
        primaryPeerIpSubnet:
          type: string
          description: Primary Peer IP Subnet
        primarySharedSecret:
          type: string
          description: Primary Shared Secret
        primaryVpnTunnel:
          type: string
          description: Primary VPN Tunnel
        secondaryBgpPeer:
          type: string
          description: Secondary BGP Peer
        secondaryPeerIp:
          type: string
          description: Secondary Peer IP
        secondaryPeerIpSubnet:
          type: string
          description: Secondary Peer IP Subnet
        secondarySharedSecret:
          type: string
          description: Secondary Shared Secret
        secondaryVpnTunnel:
          type: string
          description: Secondary VPN Tunnel
        vendor:
          type: string
          description: Vendor
    VpnOnPremiseEndpoint:
      type: object
      properties:
        primaryBgpPeer:
          type: string
          description: Primary BGP Peer
        primaryPeerIp:
          type: string
          description: Primary Peer IP
        primaryPeerIpSubnet:
          type: string
          description: Primary Peer IP Subnet
        primarySharedSecret:
          type: string
          description: Primary Shared Secret
        primaryVpnTunnel:
          type: string
          description: Primary VPN Tunnel
        secondaryBgpPeer:
          type: string
          description: Secondary BGP Peer
        secondaryPeerIp:
          type: string
          description: Secondary Peer IP
        secondaryPeerIpSubnet:
          type: string
          description: Secondary Peer IP Subnet
        secondarySharedSecret:
          type: string
          description: Secondary Shared Secret
        secondaryVpnTunnel:
          type: string
          description: Secondary VPN Tunnel
        vendor:
          type: string
          description: Vendor
