openapi: 3.0.0
info:
  description: TranquilityBase GCP DAC REST API Service
  version: "1.2"
  title: TB GCP DAC

paths:
  /health:
    get:
      operationId: gcpdac.health.check
      tags:
        - health
      summary: health check
      description: health check
      responses:
        '200':
          description: Successful

  /metadata:
    get:
      operationId: gcpdac.metadata.read_all
      tags:
        - metadata
      summary: read all metadata
      description: read all metadata
      responses:
        '200':
          description: Successful

  /solution_async/:
    post:
      operationId: gcpdac.solution.create_async
      tags:
        - solution
      summary: Create a solution
      description: Create solution in more detail - TODO
      responses:
        '201':
          description: Successfully started a solution creation task
      requestBody:
        $ref: "#/components/requestBodies/solution.solutionDetails"

  "/solution_async/{oid}":
    delete:
      operationId: gcpdac.solution.delete_async
      tags:
        - solution
      summary: delete a solution
      description: delete a solution and its resources
      parameters:
        - name: oid
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successfully started a solution deletion task

  "/solution_async/result/create/{taskid}":
    get:
      operationId: gcpdac.solution.create_solution_result
      tags:
        - solution
      summary: get create solution result
      description:  get create solution result
      parameters:
        - name: taskid
          in: path
          required: true
          schema:
            type: string
      responses:
        "201":
          description: Successfully created a solution

  "/solution_async/result/delete/{taskid}":
    get:
      operationId: gcpdac.solution.delete_solution_result
      tags:
        - solution
      summary: get delete solution result
      description:  get delete solution result
      parameters:
        - name: taskid
          in: path
          required: true
          schema:
            type: string
      responses:
        "201":
          description: Successfully deleted a solution

  /folder_async/:
    post:
      operationId: gcpdac.folder.create_async
      tags:
        - folder
      summary: Create a folder
      description: Create a folder
      responses:
        '201':
          description: Successfully started a folder creation task
      requestBody:
        $ref: "#/components/requestBodies/folder.folderDetails"

  "/folder_async/{oid}":
    delete:
      operationId: gcpdac.folder.delete_async
      tags:
        - folder
      summary: delete a folder
      description: delete a folder and its resources
      parameters:
        - name: oid
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully started a folder deletion task

  "/folder_async/result/create/{taskid}":
    get:
      operationId: gcpdac.folder.create_folder_result
      tags:
        - folder
      summary: get create folder result
      description:  get create folder result
      parameters:
        - name: taskid
          in: path
          required: true
          schema:
            type: string
      responses:
        "201":
          description: Successfully created a folder

  "/folder_async/result/delete/{taskid}":
    get:
      operationId: gcpdac.folder.delete_folder_result
      tags:
        - folder
      summary: get delete folder result
      description:  get delete folder result
      parameters:
        - name: taskid
          in: path
          required: true
          schema:
            type: string
      responses:
        "201":
          description: Successfully deleted a folder


  /vpn_async/:
    post:
      operationId: gcpdac.vpn.create_async
      tags:
        - vpn
      summary: Create a VPN
      description: Create VPN
      responses:
        '201':
          description: Successfully started a VPN creation task
      requestBody:
        $ref: "#/components/requestBodies/vpn.vpnDetails"

  "/vpn_async/{oid}":
    delete:
      operationId: gcpdac.vpn.delete_async
      tags:
        - vpn
      summary: delete a vpn
      description: delete a vpn and its resources
      parameters:
        - name: oid
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successfully started a vpn deletion task

  "/vpn_async/result/create/{taskid}":
    get:
      operationId: gcpdac.vpn.create_vpn_result
      tags:
        - vpn
      summary: get create vpn result
      description:  get create vpn result
      parameters:
        - name: taskid
          in: path
          required: true
          schema:
            type: string
      responses:
        "201":
          description: Successfully created a vpn

  "/vpn_async/result/delete/{taskid}":
    get:
      operationId: gcpdac.vpn.delete_vpn_result
      tags:
        - vpn
      summary: get delete vpn result
      description:  get delete vpn result
      parameters:
        - name: taskid
          in: path
          required: true
          schema:
            type: string
      responses:
        "201":
          description: Successfully deleted a vpn


servers:
  - url: /api
components:
  requestBodies:
    solution.solutionDetails:
      content:
        application/json:
          schema:
            x-body-name: solutionDetails
            $ref: "#/components/schemas/Solution"
    folder.folderDetails:
      content:
        application/json:
          schema:
            x-body-name: folderDetails
            $ref: "#/components/schemas/Folder"
    vpn.vpnDetails:
      content:
        application/json:
          schema:
            x-body-name: vpnDetails
            $ref: "#/components/schemas/VPN"
  schemas:
    Solution:
      type: object
      properties:
        id:
          type: integer
          description: the solution id
        name:
          type: string
          description: name
        description:
          type: string
          description: description
        businessUnit:
          type: string
          description: businessUnit
        costCentre:
          type: string
          description: costCentre
        ci:
          type: string
          description: ci
        cd:
          type: string
          description: cd
        deploymentFolderId:
          type: string
          description: deployment folder id
        sourceControl:
          type: string
          description: sourceControl
        environments:
          type: array
          description: environments
          items:
            properties:
              environment:
                type: string
                description: environment
        active:
          type: boolean
          description: active
        favourite:
          type: boolean
          description: favourite
        teams:
          type: integer
          description: teams
        lastUpdated:
          type: string
          description: "UTC/CUT last updated datetime stamp see: https://github.com/tranquilitybase-io/tb-houston-service/wiki/UTC-Timestamp"
    Folder:
      type: object
      properties:
        folder:
          type: object
          properties:
            folderName:
              type: string
              description: folder name
            parentFolderId:
              type: string
              description: parent folder id
      example:
        {
          folder: {
            folderName: 'ABC',
            parentFolderId: '236823'
          }
        }
    VPN:
      type: object
      properties:
        id:
          type: string
          description: VPN id
        vpn:
          type: object
          properties:
            bgpInterfaceNetLength:
              type: string
              description: High Availability VPN Gateway
            bgpRoutingMode:
              type: string
              description: High Availability VPN Gateway
            cloudRouterName:
              type: string
              description: High Availability VPN Gateway
            description:
              type: string
              description: High Availability VPN Gateway
            externalVpnGateway:
              type: string
              description: High Availability VPN Gateway
            googleASN:
              type: integer
              description: teams
            haVpnGateway:
              type: string
              description: High Availability VPN Gateway
            peerASN:
              type: integer
              description: High Availability VPN Gateway
            projectName:
              type: string
              description: High Availability VPN Gateway
            subnetMode:
              type: string
              description: High Availability VPN Gateway
            vpcName:
              type: string
              description: High Availability VPN Gateway
        googleSession:
          type: object
          properties:
            vpcName:
              type: string
              description: High Availability VPN Gateway
        onPremiseSession:
          type: object
          properties:
            region1:
              type: string
              description: GCP Region 1
            region2:
              type: string
              description: GCP Region 2
            network1:
              type: string
              description: Network 1
            network1Subnet1:
              type: string
              description: Network 1 Subnet 1
            network1Subnet2:
              type: string
              description: Network 1 Subnet 2
            subnet1IpCidr:
              type: string
              description: Subnet 1 IP CIDR
            subnet2IpCidr:
              type: string
              description: Subnet 2 IP CIDR
            cloudRouter:
              type: string
              description: Cloud Router
            gcpAsn:
              type: string
              description: GCP Autonomous System Number
            peerAsn:
              type: string
              description: Peer GCP Autonomous System Number
            peerGwName:
              type: string
              description: Peer Gateway Name
            peerGwInt0:
              type: string
              description: Peer Gateway Internet Address 0
            peerGwInt1:
              type: string
              description: Peer Gateway Internet Address 1
            tunnelNameIf0:
              type: string
              description: Tunnel name to on prem if 0
            tunnelNameIf1:
              type: string
              description: Tunnel name to on prem if 1
            routerInt0:
              type: string
              description: TODO
            routerInt1:
              type: string
              description: TODO
            routerIntName0:
              type: string
              description: TODO
            routerIntName1:
              type: string
              description: TODO
            bgpPeer0:
              type: string
              description: Border Gateway Protocol Peer 0
            bgpPeer1:
              type: string
              description: Border Gateway Protocol Peer 1
            sharedSecret:
              type: string
              description: Shared Secret TODO how will this work????
