swagger: "2.0"
info:
  description: TranquilityBase GCP DAC REST API Service
  version: "1.0.0"
  title: TB GCP DAC

consumes:
  - application/json
produces:
  - application/json

basePath: /api

definitions:
  Solution:
    type: object
    properties:
      id:
        type: integer
        description: id
      name:
        type: string
        description: solution name

# Paths supported by the server application
paths:
  /health:
    get:
      operationId: gcpdac.health.check
      tags: 
        - health
      summary: health check
      description: health check
      responses:
        200:
          description: Successful
  /solution:
    post:
      operationId: gcpdac.solution.create
      tags:
        - solution
      summary: Create a solution
      description: Create solution in more detail - TODO
      parameters:
        - name: solution
          in: body
          description: The solution details
          required: true
          schema:
            $ref: '#/definitions/Solution'
      responses:
        201:
          description: Successfully created a solution


